version: "1.0"
feature_name: unified-checkout-2930f501
branch: feat/unified-checkout-2930f501
repos:
    - name: demo-auth-lib
      url: https://github.com/iron-s/demo-auth-lib
      path: /Users/iron/macr-demo/demo-auth-lib
      pointer_type: sha
      current_pointer: 44810769cbbd04bda0fa093790dff090b12b51e0
      branch: feat/unified-checkout-2930f501
